### PR TITLE
add Shiny click events

### PR DESCRIPTION
**Pull request by trafficonese**
This addresses #290 

For now a click on a node, creates a Shiny input object with node id and the text content. It would be nice to have some highlighting options too. But I hope this will do as a start.

Here's a test shiny-app:
```
library(DiagrammeR)
library(shiny)

# Load in a the small repository graph
graph <-
  open_graph(
    system.file(
      "extdata/example_graphs_dgr/repository.dgr",
      package = "DiagrammeR"))

ui <- fluidPage(
  grVizOutput("dg")
  , verbatimTextOutput("print")
  , DiagrammeROutput("dg1")
  , verbatimTextOutput("print1")
)

server <- function(input, output, session) {
  output$dg <- renderGrViz({
    render_graph(graph, layout = "kk")
  })
  output$print <- renderPrint({
    req(input$dg_click)
    print(unlist(input$dg_click))
  })
  
  output$dg1 <- renderDiagrammeR({
    DiagrammeR("graph LR;A(Rounded)-->B[Squared];B-->C{A Decision};
 C-->D[Square One];C-->E[Square Two];
 style A fill:#E5E25F;  style B fill:#87AB51; style C fill:#3C8937;
 style D fill:#23772C;  style E fill:#B6E6E6;"
    )
  })
  output$print1 <- renderPrint({
    req(input$dg1_click)
    print(unlist(input$dg1_click))
  })
}

shinyApp(ui, server)
```

### CODE REVIEW

**Comment by rich-iannone** [comment]
Thank you, this is great!

**Comment by ewanwhittakerwalker** [comment]
Hello Rich Iannone! 
Thanks for writing the Diagrammer library for rShiny it's super useful, however I encountered an issue. 

I have a shiny app with multiple clickable graphs however when I use input$dg1_click$nodeValues, or input$dg2_click$nodeValues it returns the clicked values for both in the list. Any way around this? Thanks! 

Looks like there could be some problem in the code below checking the widget ID, meaning that the rshiny app cant differentiate between different diagrams clicked nodes.

https://github.com/rich-iannone/DiagrammeR/blob/d2464923c7b409bbbd1e8f67b2694a2d295c1358/inst/htmlwidgets/grViz.js

**Comment by ewanwhittakerwalker** [comment]
txt_A378 <- reactive({
    req(input$diagram_A378_click$nodeValues)
    print(unlist(input$diagram_A378_click$nodeValues))
  })
  
  output$print_A378 <- renderPrint({
    cell_pop_A378 <- txt_A378()
    cell_pop_A378 <- str_replace_all(string=cell_pop_A378, pattern=" ", repl="")
    cat("You have selected : ", cell_pop_A378)
  })

I have this duplicated for multiple graphs but nodeValues always returns the same thing.

**Comment by trafficonese** [comment]
Could you maybe come up with a small reproducible example?

**Comment by trafficonese** [comment]
yes exactly, it only works for the nodes currently.

**Comment by trafficonese** [comment]
@akshaytuptewar19 
Maybe its easier with a `reactiveValues` list.
The following example works:

<details><summary>Example</summary>
<p>

```
library(shiny)
library(DiagrammeR)
ui <- fluidPage(
  grVizOutput("dg"),
  textInput("node_label", "Enter new label"),
  actionButton("update_label", "Update label"),
  verbatimTextOutput("print")
)
server <- function(input, output, session) {
  node_labels <- reactiveValues(a = "Start", b = "Step 1", c = "Step 2", d = "Step 3", 
                                  e = "Step 4", f = "Step 5", g = "Step 6", h = "Step 7", 
                                  i = "Step 8", j = "Step 9")
  output$dg <- renderGrViz({
    grViz(paste0("
      digraph a_nice_graph {
      # node definitions with substituted label text
      node [fontname = Helvetica]
      a [label = '", node_labels$a, "']
      b [label = '", node_labels$b, "']
      c [label = '", node_labels$c, "']
      d [label = '", node_labels$d, "']
      e [label = '", node_labels$e, "']
      f [label = '", node_labels$f, "']
      g [label = '", node_labels$g, "']
      h [label = '", node_labels$h, "']
      i [label = '", node_labels$i, "']
      j [label = '", node_labels$j, "']
      # edge definitions with the node IDs
      a -> {b c d e f g h i j}
      }
      "))
  })
  observeEvent(input$update_label, {
    if (!is.null(input$dg_click)) {
      node_val <- input$dg_click$nodeValues[[1]]
      new_val <- input$node_label
      rvli <- reactiveValuesToList(node_labels)
      name <- names(rvli[rvli %in% node_val])
      which <- which(rvli %in% node_val) 
      node_labels[[name]] <- new_val
    }
  })
  txt <- reactive({
    req(input$dg_click)
    nodeval <- input$dg_click$nodeValues[[1]]
    return(paste(nodeval, " is clicked"))
  })
  output$print <- renderPrint({
    txt()
  })
}
shinyApp(ui, server)
```


</p>
</details>

**Comment by akshaytuptewar19** [comment]
i am creating separate input box for changing node label name can we update
node name by clicking on it only?

**Comment by akshaytuptewar19** [comment]
i am creating separate input box for changing node label name can we update node name by clicking on it only without creating input box separately?

**Pull request merged**
