### PR TITLE
distinct concatenation codepath for file/connection inputs

### PR DESCRIPTION
**Pull request by jjallaire**

### CODE REVIEW

**Comment by jjallaire** [comment]
Please don't merge yet (still working out some issues)

**Comment by jjallaire** [comment]
Okay, there was no problem after all. It's good to merge.

Here's what the RStudio mode looks like:

screen shot 2015-01-12 at 11 35 50 am

**Comment by rich-iannone** [comment]
That looks excellent. Thanks!

**Comment by rich-iannone** [comment]
@jjallaire this doesn't seem to work for me. I pulled the changes, rebuilt the package, created a similar plaintext file, but the rendered diagram doesn't appear in the Viewer pane. Also, don't get syntax highlighting in my "test.mmd" file @timelyportfolio could you test as well? Could be my config.

**Comment by jjallaire** [comment]
You won't see the RStudio syntax highlighting until we come out with a
daily build that supports it (still a couple of weeks away).

If you could include/attach a copy of the exact file that is failing for
you I'll try to reproduce on my end.

**Comment by rich-iannone** [comment]
Ah, makes sense. Here is an image of the file I created. It's in the working directory. Running the `DiagrammeR::DiagrammeR("test.mmd")` statement results in an empty Viewer window.

test_file

**Comment by jjallaire** [comment]
If I execute that code here's the exception that's printed to the JavaScript console:

    Uncaught Error: Parse error on line 2:
    graph LR;  A ---> B;
    ----------------^
    Expecting 'SPACE', 'PIPE', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'BRKT', 'DOT', 'PLUS', 'EQUALS', 'MULT', got 'TAGEND'

Whereas if I change the code to this everything is fine:

    graph LR;
      A --> B;

Is it possible the use of `---` as opposed to `--` is a syntax error?

This raises one other issue: when the user submits invalid mermaid syntax it seems like it would be good if they saw these error messages. I wonder if there is an easy way to just output a <pre> tag containing the error text rather than the diagram when an error is thrown?

**Comment by timelyportfolio** [comment]
Yes the mermaid parser is improving in robustness but --- is currently incorrect syntax.  The mermaid tests taught me the most about some of the flexibility and subtle syntax differences.

That is a great idea about sending the error to the widget for debugging.  I will also look into using V8 with the mermaid parser to find errors in R.

**Comment by rich-iannone** [comment]
Ah, that's right! A malformed arrow (or any other syntax error) will provide an empty diagram. Okay, I think it would be good to output the JS console output in these cases (as a start). I'll just have to look into a nice way to do so. Later on, could the syntax highlighting confirm to the user that input is correct?

**Comment by timelyportfolio** [comment]
I will look but is there a BISON implementation in R?

**Comment by rich-iannone** [comment]
@timelyportfolio @jjallaire that's great. Really appreciate the help you've provided. Really makes the whole enterprise very interesting.

**Comment by jjallaire** [comment]
You don't need bison, V8, etc. Just catch the JS error when it occurs in renderValue and then remove the  children of el and replace them with a `<pre>` tag containing the exception message.

**Comment by timelyportfolio** [comment]
Right I understand neither is necessary but I thought it might be helpful to warn of malformed syntax before rendering the widget.  Will probably spend very little time but thought it might be interesting.

**Comment by rich-iannone** [comment]
@jjallaire @timelyportfolio tested it and it works! Good stuff.
test_with_wrong_arrow_form

**Pull request merged**
