### PR TITLE
use the rstudio viewer for grViz when possible

### PR DESCRIPTION
**Pull request by jjallaire**
grViz does work with the RStudio Viewer in more recent versions of RStudio (>= 0.99.120). This is because we updated our underlying webkit engine to a much newer version based on Qt 5.4. This PR adds a check for the current version of RStudio (via the rstudioapi package) and uses the viewer for grViz when possible.

### CODE REVIEW

**Comment by rich-iannone** [comment]
@jjallaire thank you. This is a good solution.

**Comment by jjallaire** [comment]
I just added syntax highlighting and preview for GraphViz files as well (this will show up in the rstudio daily build later this week, I'll let you know when there are binaries you can try out).

**Comment by rich-iannone** [comment]
@jjallaire that's great, I look forward to seeing that!

**Comment by timelyportfolio** [comment]
very nice!

**Pull request merged**
