### PR TITLE
add feature graphviz with viz.js

### PR DESCRIPTION
**Pull request by timelyportfolio**
regarding issue #24 run with @rich-iannone 's idea of also integrating the related diagram building tool `viz.js` ;  to support both `mermaid.js` and `viz.js` rewrite `DiagrammeR` as a wrapper function with a `type` parameter and make then write `mermaid()` for the old `mermaid` functionality and `grViz` for the new `viz.js`/graphviz functionality.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@gaborcsardi, not sure if you might be interested in the quasi-"implementation" of `graphviz` in `R` with `htmlwidgets`

**Comment by gaborcsardi** [comment]
@timelyportfolio: cool, didn't know about `viz.js`. It also helps me compiling graphviz into a self-contained R package....

**Comment by timelyportfolio** [comment]
@gaborcsardi here are some examples https://github.com/timelyportfolio/DiagrammeR/blob/feature-graphviz/inst/examples/graphviz_examples.R

**Comment by rich-iannone** [comment]
Great stuff @timelyportfolio!

**Comment by timelyportfolio** [comment]
@rich-iannone  I did not pull all the new `roxygen` documentation.  Will you rerun on your end and push to `master`?  Thanks.

**Comment by timelyportfolio** [comment]
@gaborcsardi as one other note, I tried it with `V8` and I get an error that looks like it will occur on all `emscripten` javascript https://github.com/jeroenooms/V8/issues/5

**Comment by timelyportfolio** [comment]
@rich-iannone would think this also deserves an increment to maybe `0.2`

**Comment by rich-iannone** [comment]
@timelyportfolio Yes, just about to bump up the version as a tag. Changed already in DESCRIPTION. Also, added **viz.js** author into the authors list.

**Comment by rich-iannone** [comment]
@timelyportfolio all the documentation was freshly roxygenized as well.

**Pull request merged**
